[ADD] mrp_repair_partner_lot: New object "MRP repair customer lot" in…
avanzosc/mrp-repair-addons pull request #54
Opened 2019-07-05 11:22 UTC by alfredoavanzosc

… repair orders.

2019-07-08 07:21 UTC, alfredoavanzosc commented
@avanzosc/developers ... ¿alguien me puede decir porque no empieza esto?. Lo lancé el viernes, no empezó a ejecutarse, lo he vuelto a lanzar hoy, y sigue sin ejecutarse. Eskerrik asko.

2019-07-08 14:46 UTC, oihane requested changes

2019-07-08 14:46 UTC, oihane commented on mrp_repair_partner_lot/models/product_supplierinfo.py
> +        if 'show_customer_product_code' in self.env.context:
Debería de ser
```python
        if self.env.context.get('show_customer_product_code'):
```
Por si le pasas el valor como False

2019-07-08 14:46 UTC, oihane commented on mrp_repair_partner_lot/models/product_supplierinfo.py
> +                    product.product_code or '', product.product_name or '')
revisa lo que has puesto que muestre porque en caso de que no tuviese ninguno de los datos, este mostrará:
`[] `

2019-07-08 14:46 UTC, oihane commented on mrp_repair_partner_lot/views/product_supplier_info_view.xml
> +<?xml version="1.0"?>
Si no me equivoco estas vistas sobran, ya que el product_tmpl_id se hace visible al instalar **product_supplierinfo_for_customer**

2019-07-08 14:48 UTC, oihane commented on mrp_repair_partner_lot/models/mrp_repair.py
> +    repair_effectuate = fields.Text(string='Repair effectuate')
sería más correcto:
* repair_made
* repair_performed

2019-07-09 06:46 UTC, alfredoavanzosc commented on mrp_repair_partner_lot/models/product_supplierinfo.py
> +        if 'show_customer_product_code' in self.env.context:
Realizada la mejora solicitada por @oihane , eskerrik asko.

2019-07-09 06:46 UTC, alfredoavanzosc commented on mrp_repair_partner_lot/models/product_supplierinfo.py
> +                    product.product_code or '', product.product_name or '')
Realizada la mejora solicitada por @oihane . Eskerrik asko

2019-07-09 06:47 UTC, alfredoavanzosc commented on mrp_repair_partner_lot/views/product_supplier_info_view.xml
> +<?xml version="1.0"?>
@oihane .. si no lo pondo, en el fomulario de supplierinfo para clientes, no se ve el campo. Eskerrik asko.

2019-07-09 06:47 UTC, alfredoavanzosc commented on mrp_repair_partner_lot/models/mrp_repair.py
> +    repair_effectuate = fields.Text(string='Repair effectuate')
Realizada la mejora solicitada por @oihane . Eskerrik asko.

2019-07-09 06:47 UTC, closed without merging

2019-07-09 06:48 UTC, alfredoavanzosc commented
cierro este PR, porque me está dando problemas para volver a subir el módulo.l