[IMP] mrp_repair_partner_lot: New field "Repair date" in "MRP repair …
avanzosc/mrp-repair-addons pull request #58
Opened 2019-07-18 10:57 UTC by alfredoavanzosc

…customer lot" object + report customized.

2019-07-18 10:59 UTC, alfredoavanzosc commented
@avanzosc/developers ... review please.

2019-07-18 15:27 UTC, anajuaristi requested changes

2019-07-18 15:27 UTC, anajuaristi commented on mrp_repair_partner_lot/report/mrp_repair_report.xml
> +                            <div t-field="o.company_id.partner_id"
Buenas...
No entiendo este cambio
Abajo, está el o.partner_id, es decir, partner para el que se hace la reparación. Se quita de abajo y se sube arriba pero... no se pone el partner para el que se hace la reparación, sino que se muestra el partner de la compañía (o sea, nosotros mismos)
Y también el CIF de la compañía, no del partner cliente.

No digo que esté mal, digo que no entiendo el cambio, ya que se muestran 2 cosas completamente diferentes.
Aparte, el campo fecha que se ha añadido según la descripción del PR no se está incluyendo en el informe.

Ya dirás.

2019-07-19 06:26 UTC, alfredoavanzosc commented on mrp_repair_partner_lot/report/mrp_repair_report.xml
> +                            <div t-field="o.company_id.partner_id"
Muy buenos días @anajuaristi , en la parte de la cabeceraa la izquierda se saca la información de Jvv, y a la derecha de la cabecera la información del cliente.
Luego Javi me pidio poder filtar el nuevo objeto por fecha de reparación, pero no me dijo que dicha fecha tenga que aparecer en el informe.
Estas 2 cosas me las ha pedido depués de haber hecho el módulo, y haberlo probado ellos en su entorno de pruebas.

2019-07-19 11:02 UTC, anajuaristi approved these changes

2019-07-19 11:05 UTC, Daniel-CA approved these changes

2019-07-19 11:05 UTC, merged