[IMP] repair_validate: Nuevos botones, y nuevo grupo en reparaciones.
avanzosc/mrp-repair-addons pull request #69
Opened 2021-02-16 14:42 UTC by alfredoavanzosc

@avanzosc/developers ... review please

2021-02-16 14:44 UTC, Daniel-CA submitted a review, later dismissed

2021-02-16 15:29 UTC, oihane requested changes, later dismissed
Le faltan tests

2021-02-16 15:29 UTC, oihane commented on repair_validate/security/repair_validate.xml
> +        <field name="name">Permitido cerrar reparaciones</field>
Texto en castellano

2021-02-16 15:29 UTC, oihane commented on repair_validate/security/repair_validate.xml
> +        <field name="name">Permitir cerrar reparaciones</field>
Texto en castellano

2021-02-16 15:29 UTC, oihane commented on repair_validate/__init__.py
> +from . import models
Falta salto de línea

2021-02-17 08:46 UTC, anajuaristi approved these changes

2021-02-17 08:47 UTC, oihane submitted a review, later dismissed
El README no está en ingles y las traducciones no están actualizadas

2021-02-17 10:35 UTC, Daniel-CA approved these changes

2021-02-17 11:09 UTC, merged